<a href="https://colab.research.google.com/github/michelleabraham-git/Stats_minor/blob/main/Stats_16_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python

In [56]:
print("Welcome to Python") # This is a print statement. # whatever is inside the double or single quotes are considered as strings.

Welcome to Python


# Variables and expressions

In [57]:
a = 5 #this store an integer
var1 = 10.0 # this stores a float
str_var = "Alex" #this stores a string

In [58]:
a # even if dont put print and just type the variable it'll show what it contains

5

In [59]:
var1

10.0

In [60]:
str_var

'Alex'

In [61]:
# there are different data types, to see what python is doing behind the scence with the variables

In [62]:
type(a) # lists the datatype of the variable

int

In [63]:
type(var1) #note that for float variables, these decimal points if it goes to infinity, the computer memory cant really go to infinity so it stops at a point.

float

In [64]:
num1 = 1
num2 = 3
num3 = num1 / num2 # theres finite precision when it comes to floating point numbers
num3

0.3333333333333333

In [65]:
type(str_var)

str

In [66]:
# adding an int and float
y = var1 + a
y # note how the int gets converted to float

15.0

# Operators

In [67]:
p = num1+num2
q = num1 - num2
r = num1*num2
s = num1/num2
t = num1//num2 # integer division ; gives dividend
u = num1%num2 # gives remainder
print (p,q,r,s, t, u)
print ("p=",p) # old fashioned way
print (f"p= {p}") # using f string
print (" the value of p is", p) # old fashioned way
print (f" the value of p is {p}")

4 -2 3 0.3333333333333333 0 1
p= 4
p= 4
 the value of p is 4
 the value of p is 4


#Lists

In [68]:
# list is any combination of objects, it can be a combination of intergers,
int_list = [1,2,3,4] # list of integers
float_list = [1.0, 2.5, 3.7, 5.5] # list of floats
str_list = [ "a", "b", "c", "d"] # list of strings
mixed_list = [1, 2.4, "a", p] # mixed list (note that this contains the variable value of p)
int_list
float_list
str_list
mixed_list

[1, 2.4, 'a', 4]

# Aggregate functions on lists

In [69]:
sum(int_list) # sums the list

10

In [70]:
len(int_list) # gives the length of the list

4

In [71]:
int_float_list = int_list + float_list # adding two lists its basically appending one list to another, not summing, putting the lists together
int_float_list # the plus operator when used with lists does concatenation

[1, 2, 3, 4, 1.0, 2.5, 3.7, 5.5]

# Excercise - calculate the average scores


In [72]:
score = [65, 78, 90, 30]
avg_score = sum(score)/len(score) # calculating the average
avg_score
print (f"The average score of this class is {avg_score}")
max_value = max(score) # gives max value
min_value = min(score) # gives min value
print (f"The maximum score of this class is {max_value}")
print (f"The minimum score of this class is {min_value}")
print (f"The average score of this class is {avg_score}, and the class maximum is {max_value}")

The average score of this class is 65.75
The maximum score of this class is 90
The minimum score of this class is 30
The average score of this class is 65.75, and the class maximum is 90


# Functions and if statements

In [73]:
# to write functions we use def command , # putting a colon means the function starts from here
# for multiline comments we use 3 quotes, for single line comments wwe use hash (#)

def has_student_passed(score) :
  '''
  This is a multiline comment.
  This function takes the score and returns pass if
  the score if above 40.
  '''
  if score >= 40:
    print("the student has passed") # executes if, if condition evaluates to true
  else:
    print("the student has failed") # executes if, if condition evaluate to false
  return

# For loop

In [74]:
for s in score:
  print (f"the score is {s}")
  has_student_passed(s)

the score is 65
the student has passed
the score is 78
the student has passed
the score is 90
the student has passed
the score is 30
the student has failed


In [75]:
# you can also do it this way
for s in score:
  print (f"the score is {s}", {has_student_passed(s)}) # if you are putting anything in the f string that has to give a value and not just print as string you have to put the curly bracket {}
  # the none showing is the return value, if u put some value to return like 0 it'll show 0 and not none

the student has passed
the score is 65 {None}
the student has passed
the score is 78 {None}
the student has passed
the score is 90 {None}
the student has failed
the score is 30 {None}


#Homework : Write a function to calculate grades and return the grade.

In [76]:
def get_grade(score):
    '''
    This function takes the score and returns the grade.
    '''
    if score < 40:
        return "F"
    elif score <= 50:
        return "E"
    elif score <= 60:
        return "D"
    elif score <= 70:
        return "C"
    elif score <= 80:
        return "B"
    else:
        return "A"
        scores = [65, 78, 90, 30, 45, 55]

for s in score:
    print(f"Score: {s}, Grade: {get_grade(s)}")

Score: 65, Grade: C
Score: 78, Grade: B
Score: 90, Grade: A
Score: 30, Grade: F


# Getting help

In [77]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



#Dictionaries

In [78]:
names = ["Alex, Bob, Charlie", "Emma"]
# we want to map each person's nam with their score, dictionary is a data strucutre that does 1-1 mapping of key-value pairs
scores_dict = {"Alex": score[0], "Bob": score[1], "Charlie": score[2], "Emma": score[3]} # there is also another way of doing this with the zip call
scores_dict
scores_dict.keys () # gives the list of keys in the dictionary
scores_dict.values() # gives the list of values in the dictionary

dict_values([65, 78, 90, 30])

#Homework :
*   Use this dictionary along with the for loop to print the name and the score of the student
*   You can also try calculating the grade of each student inside the for block






In [79]:
## Homework answer:
names = ["Alex", "Bob", "Charlie", "Emma"]
scores = [65, 78, 90, 30]

scores_dict = dict(zip(names, scores))
def get_grade(score):
    if score < 40:
        return "F"
    elif score <= 50:
        return "E"
    elif score <= 60:
        return "D"
    elif score <= 70:
        return "C"
    elif score <= 80:
        return "B"
    else:
        return "A"
for name, score in scores_dict.items():
    grade = get_grade(score)
    print(f"Name: {name}, Score: {score}, Grade: {grade}")

Name: Alex, Score: 65, Grade: C
Name: Bob, Score: 78, Grade: B
Name: Charlie, Score: 90, Grade: A
Name: Emma, Score: 30, Grade: F


#NUMPY

In [80]:
import numpy as np #importing the numpy package


In [81]:
zeros_arr = np.zeros(10) # An array of 10 zeroes
zeros_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.



In [83]:
zeros_arr_int_2D = np.zeros(shape=(4,3), dtype=int) # a 2D array of zeroes of shape
zeros_arr_int_2D

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
ones_arr = np.ones(10) # an array of 10 ones
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(f"first array is {arr1} and its type is {type(arr1)}") #arr1 is no longer a simple list it now belongs to a new numpy class
print(f"second array is {arr2}")

first array is [1 2 3 4 5] and its type is <class 'numpy.ndarray'>
second array is [ 6  7  8  9 10]


#Numpy array operations


In [86]:
add_arr = arr1 + arr2 #here it does the element wise operations, here summing it ; adding mup arrays leads to eleement wise additon, unlike lists where lists would concetate the lists
add_arr

array([ 7,  9, 11, 13, 15])

In [87]:
sub_arr = arr1 - arr2 # it does the same element wise for subraction, and all other operations also
sub_arr

array([-5, -5, -5, -5, -5])

In [88]:
mul_arr = arr1 * arr2
mul_arr

array([ 6, 14, 24, 36, 50])

In [89]:
div_arr = arr1/arr2
div_arr

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])